language: node_js
node_js:
  - "node"

dist: trusty

branches:
  only:
    - master
    - /\d+\.\d+\.x/

cache:
  directories:
    - $HOME/.npm
    - node_modules

env:
  - TEST_SUITE=lint
  - TEST_SUITE=test-security
  - TEST_SUITE=test-unit

before_install:
  - npm i -g npm
  - npm --version

install:
  - npm i

script:
  - npm run $TEST_SUITE



